version: "3.9"
services:
  routes-service:
    build:
      context: ./routes-service
    ports:
      - "8081:8081"
    networks:
      - spring-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - checkout-service

  checkout-service:
    build:
      context: ./checkout-service
    ports:
      - "8082:8082"
    networks:
      - spring-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev

networks:
  spring-network:
    driver: bridge
